#And here's another Swagger spec fragment. 
#Maybe try benchmarking this with 10k Property0s, 
#with each property_9 containing between 0 and 10 Property9s (you'll probably want to write a script to do this)?
swagger: '2.0'
info:
  title: Nested Json spec.
  description: Nested Json schema in Swagger spec.
  version: 1.0.0
host: 0.0.0.0:8000
basePath: /myswag
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths: 
  /school:
    get:
      #tags: [School]
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/School'



definitions:
  School: 
    type: object
    properties: 
      classes: 
        type: array
        items: 
          $ref: '#/definitions/Class'

  Class:
    type: object
    #"discriminator": "property_7",
    #required: [property_7]
    properties:
      className: 
        type: string
      difficulty: 
        $ref: '#/definitions/Difficulty'
      optional: 
        type: boolean
      #"property_7": {
      # "property_8": "string"
      #},
      students: 
        type: array
        items:
          $ref: '#/definitions/Student'
        x-nullable: true

  Difficulty:
    type: string
    enum: 
      - 'Easy'
      - 'Normal'
      - 'Hard'
  Student: 
    type: object
    properties: 
      studentName: 
        type: string